### ISSUE TITLE
Possibility to disable auto generation of ids for PK

### ISSUE THREAD

**Issue by f1ght4fun** [christoforosl/codegen-lib#2]
Hi,

Currently the functionality is partially present in the code, but there are no means to activate it.

Moreover, bypassing the check by setting attribute manually on the dbmapper class still doesn't allow to insert object properly since an exception is thrown.

Please check 
Table Layout - https://cloud.githubusercontent.com/assets/12987662/21766392/ddfc252a-d676-11e6-8519-8f43239b1648.JPG

Object Values before calling save method https://cloud.githubusercontent.com/assets/12987662/21766427/29da750a-d677-11e6-8d29-600aa943e1c6.png

Exception 

{System.Data.SqlClient.SqlException (0x80131904): Cannot insert the value NULL into column 'OrderId', table 'Model.dbo.Orders'; column does not allow nulls. INSERT fails. The statement has been terminated.
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at org.model.lib.DBMapper.insert(IModelObject mo)
   at org.model.lib.DBMapper.saveModelObject(IModelObject o)
   at org.model.lib.DBMapper.save(IModelObject o)
   at DataModel.App.OrdersDBMapper.saveOrders(Orders mo)

**Comment by christoforosl** [comment]
This was fixed, in version 4.0.18.10 of code generator.  Please run generation using the latest generator from the publish web site

**Comment by f1ght4fun** [comment]
I just used the new installer, however the attribute was still not generated and I continue to get same exception. 

Any other suggestions ?

**Comment by christoforosl** [comment]
The new installer or the new generator?  You need to run the new generator.

What happens if you checkout the project and build it from github sources ?
As you will see from the source code, there is a new test table called
TestTableNoIncrement
. That table generated correctly, see:
https://github.com/christoforosl/codegen-lib/commit/60cf4f9c2189467580d8fdefcb244072f477cd3c


[image: Inline image 1]


Notice: [AttrIsPrimaryKeyAutogenerated(false)] added line in file history

**Comment by f1ght4fun** [comment]
Issue resolved, my bad - was using incorrect xml tag.

Tnx!
